import { Providers } from "@/redux/provider";
import Header from "./components/Header";
import "./globals.css";
import Components from "./components/Components";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          <Components>{children}</Components>
        </Providers>
      </body>
    </html>
  );
}
